[template]

VUE_APP_ABOUT_IMAGE=https://media.licdn.com/dms/image/C4E03AQHrouWw4QWN8Q/profile-displayphoto-shrink_800_800/0/1611784379011?e=1699488000&v=beta&t=UJgJpVoyGNijn7pYFKnKbeeztOmty06PkoBu5IBgUu8

VUE_APP_PROJECT_IMG=https://w7.pngwing.com/pngs/102/272/png-transparent-gear-the-noun-project-icon-gears-transport-rim-transportation.png

VUE_APP_BLOG_IMG=https://www.pngfind.com/pngs/m/269-2693798_png-file-svg-blog-vector-icon-png-transparent.png

VUE_APP_GIT_ICON=https://img.icons8.com/external-tanah-basah-glyph-tanah-basah/48/null/external-github-social-media-tanah-basah-glyph-tanah-basah.png

VUE_APP_LINKED_ICON=https://img.icons8.com/ios/50/null/linkedin.png

VUE_APP_MEDIUM_ICON=https://img.icons8.com/ios/50/null/medium-logo.png

VUE_APP_YT_ICON=https://img.icons8.com/ios-filled/50/null/youtube-play.png

VUE_APP_GIT=https://github.com/Ginger-Mano

VUE_APP_LINKED=https://www.linkedin.com/in/manon-casimir-sainton

VUE_APP_MEDIUM=https://mcasimirian.medium.com/

VUE_APP_YT=https://www.youtube.com/channel/UC7giI4VW75cI-_-uqY_aRoQ

VUE_APP_SPOTZ=https://www.youtube.com/embed/pRNGNh_npa0

VUE_APP_WILDLIFE=https://www.youtube.com/embed/7xE0sdlucyI

VUE_APP_SPOTZ_GIT=https://github.com/Ginger-Mano/Mod2Project

VUE_APP_WILD_FRONT=https://github.com/Ginger-Mano/WildlifeKeep-Frontend2/blob/main/src/App.js

VUE_APP_WILD_BACK=https://github.com/Ginger-Mano/The-Wildlife-Keep-Backend

VUE_APP_DESTRUCTURING=https://medium.com/javascript-in-plain-english/applying-basic-destructuring-in-react-ede119aab03e

VUE_APP_COLOR=https://mcasimirian.medium.com/a-brief-intro-to-color-theory-f25fd3479bd2

VUE_APP_JSX=https://mcasimirian.medium.com/the-basics-of-using-jsx-in-react-js-578db41ec625

VUE_APP_CREATIVES=https://mcasimirian.medium.com/5-tips-for-creatives-navigating-a-coding-bootcamp-58b2e19bbcf0
